### ISSUE TITLE
Put on PiPy

### ISSUE THREAD

**Issue by audrow** [audrow/nylas-email-keyword-matcher#6]
After the following are completed, it would be great to put this project on PyPi: 
- [ ] #3 Add readme
- [ ] #1 Add CI
- [ ] #5 Add code coverage
- [ ] #2 Add tests for `NylasEmailKeywordMatcher` class
- [ ] #4 Add Flake8 and PEP257 tests
